### ISSUE TITLE
Feedback Task Pertemuan 3

### ISSUE THREAD

**Issue by aufaroot18** [febryan3131/tugas-frontend#1]
## Perbaikan

- Pada method `find`, gunakan parameter `name` untuk membandingkan data.

## Improvement (Hal yang bisa ditingkatkan)

- Pada fungsi `map` di `formatUser`, dapat menggunakan spread operator untuk mengupdate object. Ex: ``{ ...user, name: `${title}. ${user.name}` }``
- Return pada arrow function bisa dipersingkat menjadi sebaris

**Comment by febryan3131** [comment]
Baik kak terima kasih insyaaAllah saya perbaiki

Pada tanggal Kam, 21 Apr 2022 17:06, Aufa Billah ***@***.***>
menulis:

**Comment by aufaroot18** [comment]
Baik sama-sama.
